theme: minima
title: Ellienndea's blog
author: Linda
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  On my way to become a web developer. HTML, CSS, Javascript, Git, accessibility, responsive websites, freeCodeCamp Berlin, CSS Battle

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
